UPDATE flyway_schema_history SET success = success;

ALTER TABLE dbo.user_accounts ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.user_accounts ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.parent_profiles ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.parent_profiles ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.student_profiles ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.student_profiles ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.parent_student_links ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.parent_student_links ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.subjects ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.subjects ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.tutor_profiles ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.tutor_profiles ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.tutor_availabilities ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.tutor_availabilities ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.tutor_subjects ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.tutor_subjects ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.bookings ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.bookings ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.payments ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.payments ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;

ALTER TABLE dbo.reviews ALTER COLUMN created_at DATETIMEOFFSET(6) NOT NULL;
ALTER TABLE dbo.reviews ALTER COLUMN updated_at DATETIMEOFFSET(6) NOT NULL;
